inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

#--------------------------------

Layout/SpaceInsideReferenceBrackets:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: false

Layout/ArrayAlignment:
  Exclude:
    - 'test/test_vgparser.rb'

Layout/FirstArrayElementIndentation:
  Exclude:
    - 'test/test_vgparser.rb'

Layout/MultilineArrayBraceLayout:
  Exclude:
    - 'test/test_vgparser.rb'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/HashAlignment:
  Enabled: false

Layout/SpaceBeforeSemicolon:
  Enabled: false

# --------------------------------

Lint/UselessAssignment:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

#--------------------------------

Naming/MethodParameterName:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - 'vgvm.rb'

Naming/HeredocDelimiterNaming:
  Exclude:
    - 'test/test_vgparser.rb'

Naming/VariableNumber:
  Exclude:
    - 'test/test_vgparser.rb'

#--------------------------------

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TernaryParentheses:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ConditionalAssignment:
  Exclude:
    - 'gol.rb'

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Exclude:
    - 'vgcg.rb'

Style/Encoding:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'

Style/IfUnlessModifier:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/Semicolon:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

#--------------------------------

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - 'vgvm.rb'

Style/WhileUntilModifier:
  Enabled: false

#--------------------------------

Security/Open:
  Enabled: false
