ignore:
  - "**/*":
    - Layout/ExtraSpacing
    - Layout/SpaceInsideParens
    - Lint/SymbolConversion
    - Style/GlobalVars
    - Style/MethodCallWithoutArgsParentheses
    - Style/StderrPuts
    - Layout/SpaceBeforeSemicolon
    # TODO
    - Layout/ArrayAlignment
    - Layout/FirstArrayElementIndentation
    - Layout/MultilineArrayBraceLayout
    - Layout/MultilineMethodCallIndentation
    - Layout/SpaceAroundOperators
    - Layout/SpaceInsideHashLiteralBraces
    - Layout/SpaceInsideRangeLiteral
    - Layout/SpaceInsideReferenceBrackets
    - Layout/SpaceInsideStringInterpolation
    - Lint/UselessAssignment
    - Performance/ReverseEach
    - Performance/StringReplacement
    - Security/Open
    - Style/ConditionalAssignment
    - Style/EmptyCaseCondition
    - Style/EmptyElse
    - Style/HashSyntax
    - Style/IfInsideElse
    - Style/NegatedWhile
    - Style/RedundantBegin
    - Style/RedundantParentheses
    - Style/SelfAssignment
    - Style/Semicolon
    - Style/SlicingWithRange
    - Style/TernaryParentheses
