#!/bin/bash

set -o errexit
set -o nounset

print_this_dir() {
  (
    cd "$(dirname $0)"
    pwd
  )
}

get_envvar() {
  local name="$1"; shift
  local default_value="$1"; shift

  if (env | grep "^${name}=" > /dev/null); then
    eval 'echo $'"$name"
  else
    echo $default_value
  fi
}

__DIR__="$(print_this_dir)"

TMP_DIR=${__DIR__}/tmp/
PRINT_ASM=$(get_envvar "PRINT_ASM" 0)

mkdir -p ${TMP_DIR}

file="$1"
bname=pricc-rb

src_temp=${TMP_DIR}/${bname}.pric.rb

# TODO check input_max
ruby ${__DIR__}/check.rb gvar-width $file
ruby ${__DIR__}/preproc.rb $file > $src_temp

tokensfile=${TMP_DIR}/${bname}.vgtok.txt
treefile=${TMP_DIR}/${bname}.vgt.json
asmfile=${TMP_DIR}/${bname}.vga.txt
exefile=${TMP_DIR}/${bname}.vge.txt

ruby ${__DIR__}/vglexer.rb $src_temp > $tokensfile
ruby ${__DIR__}/vgparser.rb $tokensfile > $treefile

ruby ${__DIR__}/check.rb fn-sig $treefile

if [ $PRINT_ASM -eq 1 ]; then
  ruby ${__DIR__}/vgcg.rb $treefile
else
  ruby ${__DIR__}/vgcg.rb $treefile > $asmfile

  ruby ${__DIR__}/vgasm.rb $asmfile
fi
