#!/bin/bash

set -o errexit
set -o nounset

print_this_dir() {
  (
    cd "$(dirname $0)"
    pwd
  )
}

get_envvar() {
  local name="$1"; shift
  local default_value="$1"; shift

  if (env | grep "^${name}=" > /dev/null); then
    eval 'echo $'"$name"
  else
    echo $default_value
  fi
}

run() {
  local name="$1"; shift
  local infile="$1"; shift
  local outfile="$1"; shift

  echo "-->> ${name}" >&2

  # time (
  #   printf "${name} ... "

  STDIN=$infile DEBUG=0 VERBOSE=0 \
    $PRICVM ${__DIR__}/exe/${name}.exe.txt > $outfile

  #   printf "done\n"
  #   printf "\n"
  # ) >&2
}

__DIR__="$(print_this_dir)"

TMP_DIR=${__DIR__}/tmp/
PRICVM=${__DIR__}/../pricvm
PRINT_ASM=$(get_envvar "PRINT_ASM" 0)

mkdir -p ${TMP_DIR}

file="$1"
bname=pricc-pric

src_temp=${TMP_DIR}/${bname}.pric.rb
tokensfile=${TMP_DIR}/${bname}.tokens.txt
treefile=${TMP_DIR}/${bname}.vgt.json
asmfile=${TMP_DIR}/${bname}.vga.txt

rake build-all

ruby ${__DIR__}/../check.rb gvar-width $file
ruby ${__DIR__}/../preproc.rb $file > $src_temp

run "lexer" $src_temp $tokensfile

run "parser" $tokensfile $treefile

ruby ${__DIR__}/../check.rb fn-sig $treefile
run "codegen" $treefile $asmfile

if [ $PRINT_ASM -eq 1 ]; then
  cat $asmfile
else
  ruby ${__DIR__}/../vgasm.rb $asmfile
fi
